import { 
  FaFacebookF, FaTwitter, FaLinkedinIn, FaInstagram, FaWhatsapp, 
  FaMapMarkerAlt, FaPhone, FaEnvelope, FaClock, FaArrowRight, 
  FaCode, FaHeart, FaSnapchat, FaPalette, FaLaptopCode, 
  FaMobileAlt, FaDatabase, FaServer, FaShieldAlt, FaRocket, 
  FaHandshake, FaLightbulb, FaGem, FaProjectDiagram, FaUsers, 
  FaSmile, FaTrophy, FaGlobe, FaPaperPlane, FaUser, 
  FaBuilding, FaCommentAlt, FaCheckCircle, FaDirections, FaChevronDown,
  FaCogs, FaTools, FaChartBar, FaCloud, FaSearch, FaBell, FaCamera, FaVideo,
  FaFileAlt, FaFolder, FaTrash, FaEdit, FaPlus, FaMinus, FaDownload, FaUpload,
  FaBriefcase, FaGraduationCap, FaHome, FaInfoCircle, FaQuestionCircle,
  FaExclamationTriangle, FaCheck, FaTimes, FaLock, FaLockOpen, FaKey, FaLink, FaUnlink,
  FaShareAlt, FaEye, FaEyeSlash, FaCoffee, FaBeer, FaDesktop, FaTabletAlt, FaMobile,
  FaGamepad, FaMusic, FaHeadphones, FaMicrophone, FaPrint, FaWifi, FaBluetooth, FaPlug,
  FaBatteryFull, FaMicrochip, FaMemory, FaDatabase as FaDb, FaNetworkWired, FaCloudDownloadAlt,
  FaCloudUploadAlt, FaShoppingCart, FaCreditCard, FaUserPlus, FaUserMinus, FaUserShield,
  FaUserFriends, FaUserGraduate, FaUserTie, FaUserSecret, FaBrain, FaRobot, FaFingerprint,
  FaBug, FaCodeBranch, FaTerminal, FaLaptop, FaSitemap, FaMicroscope, FaStethoscope, FaFlask,
  FaLightbulb as FaIdea, FaRocket as FaLaunch, FaSpaceShuttle, FaPlane, FaShip, FaCar, FaTruck,
  FaBicycle, FaWalking, FaStore, FaHotel, FaUtensils, FaMap, FaGlobeAmericas, FaGlobeEurope, FaGlobeAsia
} from 'react-icons/fa';

import {
  SiReact, SiJavascript, SiNodedotjs, SiPython, SiDocker, 
  SiGit, SiTypescript, SiAngular, SiVuedotjs, SiNextdotjs,
  SiTailwindcss, SiBootstrap, SiSass, SiHtml5, SiCss3, SiPhp,
  SiLaravel, SiPostgresql, SiMysql, SiMongodb, SiRedis, SiFirebase,
  SiGooglecloud, SiDigitalocean, SiNetlify,
  SiVercel, SiLinux, SiUbuntu, SiCentos, SiFedora, SiDebian,
 SiApple, SiAndroid, SiFigma, SiAdobephotoshop, SiAdobeillustrator,
  SiAdobeaftereffects, SiAdobepremierepro, SiPostman,
  SiIntellijidea, SiPycharm, SiVim, SiGnubash, SiJquery, SiRedux, SiGraphql
} from 'react-icons/si';

import { 
  BsCodeSlash, BsShieldCheck, BsHeadset, BsRocketTakeoff, 
  BsGear, BsLockFill, BsBriefcaseFill, BsChatLeftDotsFill, 
  BsDisplayFill, BsLaptopFill, BsPhoneFill, BsTvFill, BsCpuFill, 
  BsGridFill, BsKanbanFill, BsLightningFill, BsMagic, BsCloudCheckFill,
  BsPeopleFill, BsPersonFill, BsStarFill, BsSunFill, BsMoonFill, 
  BsHandThumbsUpFill, BsHeartFill, BsEnvelopeFill, BsTelephoneFill, 
  BsGeoAltFill, BsCalendarFill, BsGraphUp, BsGraphDown, BsWalletFill
} from 'react-icons/bs';

import { IoCloseCircleOutline, IoSettingsOutline, IoNotificationsOutline, IoSearchOutline, IoMenuOutline } from 'react-icons/io5';

import { HiOutlineLightBulb, HiOutlineDatabase, HiOutlineCloud } from 'react-icons/hi';

import { MdOutlineDeveloperMode, MdOutlineSecurity, MdOutlineAnalytics } from 'react-icons/md';

export const iconMap = {
  // Font Awesome Icons
  facebook: FaFacebookF,
  twitter: FaTwitter,
  linkedin: FaLinkedinIn,
  instagram: FaInstagram,
  whatsapp: FaWhatsapp,
  snapchat: FaSnapchat,
  mapMarker: FaMapMarkerAlt,
  phone: FaPhone,
  envelope: FaEnvelope,
  clock: FaClock,
  arrowRight: FaArrowRight,
  code: FaCode,
  heart: FaHeart,
  palette: FaPalette,
  laptopCode: FaLaptopCode,
  mobileAlt: FaMobileAlt,
  database: FaDatabase,
  server: FaServer,
  shieldAlt: FaShieldAlt,
  rocket: FaRocket,
  handshake: FaHandshake,
  lightbulb: FaLightbulb,
  gem: FaGem,
  projectDiagram: FaProjectDiagram,
  users: FaUsers,
  smile: FaSmile,
  trophy: FaTrophy,
  globe: FaGlobe,
  paperPlane: FaPaperPlane,
  user: FaUser,
  building: FaBuilding,
  commentAlt: FaCommentAlt,
  checkCircle: FaCheckCircle,
  directions: FaDirections,
  chevronDown: FaChevronDown,
  cogs: FaCogs,
  tools: FaTools,
  chartBar: FaChartBar,
  cloud: FaCloud,
  search: FaSearch,
  bell: FaBell,
  camera: FaCamera,
  video: FaVideo,
  fileAlt: FaFileAlt,
  folder: FaFolder,
  trash: FaTrash,
  edit: FaEdit,
  plus: FaPlus,
  minus: FaMinus,
  download: FaDownload,
  upload: FaUpload,
  briefcase: FaBriefcase,
  graduationCap: FaGraduationCap,
  home: FaHome,
  infoCircle: FaInfoCircle,
  questionCircle: FaQuestionCircle,
  exclamationTriangle: FaExclamationTriangle,
  check: FaCheck,
  times: FaTimes,
  lock: FaLock,
  lockOpen: FaLockOpen,
  key: FaKey,
  link: FaLink,
  unlink: FaUnlink,
  shareAlt: FaShareAlt,
  eye: FaEye,
  eyeSlash: FaEyeSlash,
  coffee: FaCoffee,
  beer: FaBeer,
  desktop: FaDesktop,
  tabletAlt: FaTabletAlt,
  mobile: FaMobile,
  gamepad: FaGamepad,
  music: FaMusic,
  headphones: FaHeadphones,
  microphone: FaMicrophone,
  print: FaPrint,
  wifi: FaWifi,
  bluetooth: FaBluetooth,
  plug: FaPlug,
  batteryFull: FaBatteryFull,
  microchip: FaMicrochip,
  memory: FaMemory,
  db: FaDb,
  networkWired: FaNetworkWired,
  cloudDownload: FaCloudDownloadAlt,
  cloudUpload: FaCloudUploadAlt,
  shoppingCart: FaShoppingCart,
  creditCard: FaCreditCard,
  userPlus: FaUserPlus,
  userMinus: FaUserMinus,
  userShield: FaUserShield,
  userFriends: FaUserFriends,
  userGraduate: FaUserGraduate,
  userTie: FaUserTie,
  userSecret: FaUserSecret,
  brain: FaBrain,
  robot: FaRobot,
  fingerprint: FaFingerprint,
  bug: FaBug,
  codeBranch: FaCodeBranch,
  terminal: FaTerminal,
  laptop: FaLaptop,
  sitemap: FaSitemap,
  microscope: FaMicroscope,
  stethoscope: FaStethoscope,
  flask: FaFlask,
  idea: FaIdea,
  launch: FaLaunch,
  spaceShuttle: FaSpaceShuttle,
  plane: FaPlane,
  ship: FaShip,
  car: FaCar,
  truck: FaTruck,
  bicycle: FaBicycle,
  walking: FaWalking,
  store: FaStore,
  hotel: FaHotel,
  utensils: FaUtensils,
  map: FaMap,
  globeAmericas: FaGlobeAmericas,
  globeEurope: FaGlobeEurope,
  globeAsia: FaGlobeAsia,

  // Simple Icons (Tech Stacks)
  react: SiReact,
  javascript: SiJavascript,
  nodejs: SiNodedotjs,
  python: SiPython,
  docker: SiDocker,
  git: SiGit,
  typescript: SiTypescript,
  angular: SiAngular,
  vue: SiVuedotjs,
  nextjs: SiNextdotjs,
  tailwindcss: SiTailwindcss,
  bootstrap: SiBootstrap,
  sass: SiSass,
  html5: SiHtml5,
  css3: SiCss3,
  php: SiPhp,
  laravel: SiLaravel,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  redis: SiRedis,
  firebase: SiFirebase,
  googlecloud: SiGooglecloud,
  digitalocean: SiDigitalocean,
  netlify: SiNetlify,
  vercel: SiVercel,
  linux: SiLinux,
  ubuntu: SiUbuntu,
  centos: SiCentos,
  fedora: SiFedora,
  debian: SiDebian,
  apple: SiApple,
  android: SiAndroid,
  figma: SiFigma,
  photoshop: SiAdobephotoshop,
  illustrator: SiAdobeillustrator,
  aftereffects: SiAdobeaftereffects,
  premiere: SiAdobepremierepro,
  postman: SiPostman,
  intellij: SiIntellijidea,
  pycharm: SiPycharm,
  vim: SiVim,
  bash: SiGnubash,
  jquery: SiJquery,
  redux: SiRedux,
  graphql: SiGraphql,

  // Bootstrap Icons
  codeSlash: BsCodeSlash,
  shieldCheck: BsShieldCheck,
  headset: BsHeadset,
  rocketTakeoff: BsRocketTakeoff,
  gear: BsGear,
  lockFill: BsLockFill,
  briefcaseFill: BsBriefcaseFill,
  chatDots: BsChatLeftDotsFill,
  displayFill: BsDisplayFill,
  laptopFill: BsLaptopFill,
  phoneFill: BsPhoneFill,
  tvFill: BsTvFill,
  cpuFill: BsCpuFill,
  gridFill: BsGridFill,
  kanbanFill: BsKanbanFill,
  lightningFill: BsLightningFill,
  magic: BsMagic,
  cloudCheck: BsCloudCheckFill,
  peopleFill: BsPeopleFill,
  personFill: BsPersonFill,
  starFill: BsStarFill,
  sunFill: BsSunFill,
  moonFill: BsMoonFill,
  thumbsUp: BsHandThumbsUpFill,
  heartFill: BsHeartFill,
  envelopeFill: BsEnvelopeFill,
  telephoneFill: BsTelephoneFill,
  geoAltFill: BsGeoAltFill,
  calendarFill: BsCalendarFill,
  graphUp: BsGraphUp,
  graphDown: BsGraphDown,
  wallet: BsWalletFill,

  // Ionicons 5
  closeCircle: IoCloseCircleOutline,
  settings: IoSettingsOutline,
  notifications: IoNotificationsOutline,
  searchOutline: IoSearchOutline,
  menu: IoMenuOutline,

  // Hero Icons
  ideaOutline: HiOutlineLightBulb,
  dbOutline: HiOutlineDatabase,
  cloudOutline: HiOutlineCloud,

  // Material Design Icons
  devMode: MdOutlineDeveloperMode,
  security: MdOutlineSecurity,
  analytics: MdOutlineAnalytics
};
